name: CI build
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/release.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1.x
          dune-cache: true
      - run: make deps
      - run: make test
      - run: make dev release
      - uses: actions/upload-artifact@v2
        with:
          name: ffbar-ubuntu-linux-x86_64
          path: _build/default/bin/main.exe
          if-no-files-found: error
